name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node-app-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
 
  publish-docker:
    runs-on: ubuntu-latest
    needs: ['node-app-compile']
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: peterjakubik/${{ secrets.TAG_NAME }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
  container-scan:
    runs-on: ubuntu-latest
    needs: ['publish-docker']
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Anchore Container Scan
      uses: anchore/scan-action@main
      with:
         image: peterjakubik/${{ secrets.TAG_NAME }}
         acs-report-enable: true
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
