name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker build . --file Dockerfile --tag $${{ secrets.TAG_NAME }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: peterjakubik/$${{ secrets.TAG_NAME }}
        tag_with_ref: true
